function stereoParams = createStereoParams()
B = 160;
fl = 33.52; %mm
desiredRes = 0.02;
pxPitch = 0.0022;
WD = fl* desiredRes/pxPitch;
theta = -(pi/2-acos(B/(2*WD)))*2;
N = 8;   

p = [1944 2592]./2;
R1=  eye(3);
T1 = [0 0 0];
R2 = [cos(theta) 0 sin(theta); 0 1 0; -sin(theta) 0 cos(theta)]; %[1 0 0; 0 cos(delta) -sin(delta); 0 sin(delta) cos(delta)]; % params.RotationOfCamera2;
T2 = -[B*cos(theta/2), 0, B*sin(theta/2)] ;

f = [fl/pxPitch, fl/pxPitch]; 
intrinsics = [f(1), 0, p(1);
                0, f(2), p(2);
                0, 0, 1]'; % mm,
                      
camParams1 = struct('ImageSize', [1944,2592], ...
                    'RadialDistortion', [-0.0289, -0.2827],...
                    'TangentialDistortion', [0,0],...
                    'WorldUnits', 'mm',...
                    'EstimateSkew', 0, ...
                    'NumRadialDistortionCoefficients', 2,...
                    'EstimateTangentialDistortion', 0, ...
                    'IntrinsicMatrix', intrinsics, ...
                    'FocalLength', f, ...
                    'PrincipalPoint', p, ...
                    'Skew', 0, ...
                    'MeanReprojectionError', 0.3453);
                
camParams2 = struct('ImageSize', [1944,2592], ...
                    'RadialDistortion', [0.0167, -2.7034],...
                    'TangentialDistortion', [0,0],...
                    'WorldUnits', 'mm',...
                    'EstimateSkew', 0, ...
                    'NumRadialDistortionCoefficients', 2,...
                    'EstimateTangentialDistortion', 0, ...
                    'IntrinsicMatrix', intrinsics, ...
                    'FocalLength', f, ...
                    'PrincipalPoint', p, ...
                    'Skew', 0, ...
                    'MeanReprojectionError', 0.3453);

[~, lCameraPos] = extrinsicsToCameraPose(R1, T1);
[~, rCameraPos] = extrinsicsToCameraPose(R2, T2);
camPoses = [lCameraPos; rCameraPos];
cameraMatrix1 = [R1; T1]*intrinsics;
cameraMatrix2 = [R2; T2]*intrinsics;
camMatrix = zeros([2, size(cameraMatrix1)]);
camMatrix(1, :, :) = cameraMatrix1;
camMatrix(2, :, :) = cameraMatrix2; 

stereoParams = struct('CameraParameters1', camParams1, ...
                      'CameraParameters2', camParams2, ...
                      'RotationOfCamera2', R2, ...
                      'TranslationOfCamera2', T2, ...
                      'camPoses', camPoses,...
                      'camMatrix', camMatrix, ...
                      'N', 8,...
                      'WD', WD,...
                      'fl', fl,...
                      'B', B,...
                      'desiredRes', desiredRes,...
                      'theta', theta,...
                      'pxPitch', pxPitch);
end