function stereoParams = createStereoParams()
% CREATE STEREO PARAMS Based on the calucation made in the thesis,
% we create a set of stero camera parameters.

% Baseline
B = 160; %mm
% Focal Length
fl = 33.52; %mm
desiredRes = 0.02; % mm/px
pxPitch = 0.0022; % mm
% Working Distance
WD = fl* desiredRes/pxPitch; 
% Pan Angle
theta = -(pi/2-acos(B/(2*WD)))*2;

% center point on the image sensor
p = [1944 2592]./2;
% Left Rotational Matrix
R1=  eye(3);
% Left Translational Matrix
T1 = [0 0 0];
% Right Rotational Matrix based on the pan angle
R2 = [cos(theta) 0 sin(theta); 0 1 0; -sin(theta) 0 cos(theta)]; %[1 0 0; 0 cos(delta) -sin(delta); 0 sin(delta) cos(delta)]; % params.RotationOfCamera2;
% Right Translational Matrix based on the baseline and the pan angle
T2 = -[B*cos(theta/2), 0, B*sin(theta/2)] ;
% focal length in pixels
f = [fl/pxPitch, fl/pxPitch]; 
intrinsics = [f(1), 0, p(1);
                0, f(2), p(2);
                0, 0, 1]'; % mm,
% left camera                      
camParams1 = struct('ImageSize', [1944,2592], ...
                    'RadialDistortion', [-0.0289, -0.2827],...
                    'TangentialDistortion', [0,0],...
                    'WorldUnits', 'mm',...
                    'EstimateSkew', 0, ...
                    'NumRadialDistortionCoefficients', 2,...
                    'EstimateTangentialDistortion', 0, ...
                    'IntrinsicMatrix', intrinsics, ...
                    'FocalLength', f, ...
                    'PrincipalPoint', p, ...
                    'Skew', 0, ...
                    'MeanReprojectionError', 0.3453);
% right camera                
camParams2 = struct('ImageSize', [1944,2592], ...
                    'RadialDistortion', [0.0167, -2.7034],...
                    'TangentialDistortion', [0,0],...
                    'WorldUnits', 'mm',...
                    'EstimateSkew', 0, ...
                    'NumRadialDistortionCoefficients', 2,...
                    'EstimateTangentialDistortion', 0, ...
                    'IntrinsicMatrix', intrinsics, ...
                    'FocalLength', f, ...
                    'PrincipalPoint', p, ...
                    'Skew', 0, ...
                    'MeanReprojectionError', 0.3453);
% create camera positions matrix
[~, lCameraPos] = extrinsicsToCameraPose(R1, T1);
[~, rCameraPos] = extrinsicsToCameraPose(R2, T2);
camPoses = [lCameraPos; rCameraPos];
cameraMatrix1 = [R1; T1]*intrinsics;
cameraMatrix2 = [R2; T2]*intrinsics;
camMatrix = zeros([2, size(cameraMatrix1)]);
camMatrix(1, :, :) = cameraMatrix1;
camMatrix(2, :, :) = cameraMatrix2; 
% dof: depth of field +/- 30mm
% F-stop: 8
stereoParams = struct('CameraParameters1', camParams1, ...
                      'CameraParameters2', camParams2, ...
                      'RotationOfCamera2', R2, ...
                      'TranslationOfCamera2', T2, ...
                      'camPoses', camPoses,...
                      'camMatrix', camMatrix, ...
                      'N', 8,...
                      'WD', WD,...
                      'fl', fl,...
                      'B', B,...
                      'desiredRes', desiredRes,...
                      'theta', theta,...
                      'pxPitch', pxPitch,...
                      'dof', 30);
end